### ISSUE TITLE
SUBTLETY - css organization

### ISSUE THREAD

**Issue by franfranfranfran** [tripin2/prj-rev-bwfs-tea-cozy#1]
https://github.com/tripin2/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L1-L148

good idea to use comments and organize your css. a more helpful system in the long run would be to organize your css by which section on the page they belong to. so, sections for the header, tea, locations, etc...

**Comment by tripin2** [comment]
good suggestion, I thought this when reading your previous comments, so now I know the best option, I will try to keep that in mind and make it better every time I will do sth like this
