### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [tripin2/prj-rev-bwfs-tea-cozy#3]
https://github.com/tripin2/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L62-L66

great job using flex display to align items in several sections of the page. is there a way we can avoid setting the flex styling for every section that uses it? check out the styling associated with container and see if you can use that for the other flex sections.

**Comment by tripin2** [comment]
yeah, I realized now how many repeated lines I used that could be simplified and therefore more concise and easier to follow and edit later.. I will try to do better next time, I need to improve this
