### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [tripin2/prj-rev-bwfs-tea-cozy#5]
**GRADE**: Meets Expectations

**SUMMARY**: Great job on this project! The site itself looks great and you did an excellent job keeping both your project folder and the files themselves organized and readable. Very good use of flex display throughout the page as well.

   Behind the scenes in your html / css, try to keep in mind DRY principles. Keep an eye out for ways to reduce repeated lines of styling. In your css, try to keep your code organized by what section it belongs to in your html. This will help greatly if you ever need to modify a value or otherwise need to find something specific later on.

   From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Keep up the great work!

**Comment by tripin2** [comment]
thank you for the review and for a suggestion, I will look at Bootstrap navigation bar
